CREATE TABLE [dbo].[Books]
(
	[ISBN] NVARCHAR (50) NOT NULL,
	[BookTitle] NVARCHAR(100) NOT NULL,
	[YearPublished] INT NOT NULL,
	[AuthorID] INT NOT NULL,
	[AuthorFirstName] NVARCHAR(50) NOT NULL,
	[AuthorSurName] NVARCHAR(50) NOT NULL,
	[AuthorTFN] NVARCHAR(12) NOT NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY (ISBN)
)

