CREATE TABLE [dbo].[Loans]
(
	[StudentID] NVARCHAR(9) NOT NULL,
	[ISBN] NVARCHAR (50) NOT NULL,
	[DateBorrowed] DATE NOT NULL,
	CONSTRAINT PK_LOAN PRIMARY KEY (StudentID, ISBN, DateBorrowed),
	CONSTRAINT FK_LOAN_STUDENT FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
	CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (ISBN) REFERENCES Books(ISBN)
)
